const WORD_DATABASE = [
  {
    name: "A1 - Başlangıç",
    description: "Temel kelime bilgisi ve basit cümleler",
    color: "#4CAF50",
    icon: "🌱",
    words: [
      { english: "Hello", turkish: "Merhaba", example: "Hello, how are you?", exampleTurkish: "Merhaba, nasılsınız?", partOfSpeech: "interjection", phonetics: "/həˈloʊ/" },
      { english: "Goodbye", turkish: "Hoşça kal", example: "Goodbye, see you tomorrow!", exampleTurkish: "Hoşça kal, yarın görüşürüz!", partOfSpeech: "interjection", phonetics: "/ɡʊdˈbaɪ/" },
      { english: "Please", turkish: "Lütfen", example: "Please sit down.", exampleTurkish: "Lütfen oturun.", partOfSpeech: "adverb", phonetics: "/pliːz/" },
      { english: "Thank you", turkish: "Teşekkürler", example: "Thank you for your help.", exampleTurkish: "Yardımınız için teşekkürler.", partOfSpeech: "interjection", phonetics: "/θæŋk juː/" },
      { english: "Yes", turkish: "Evet", example: "Yes, I understand.", exampleTurkish: "Evet, anlıyorum.", partOfSpeech: "adverb", phonetics: "/jɛs/" },
      { english: "No", turkish: "Hayır", example: "No, thank you.", exampleTurkish: "Hayır, teşekkürler.", partOfSpeech: "adverb", phonetics: "/noʊ/" },
      { english: "Water", turkish: "Su", example: "I need a glass of water.", exampleTurkish: "Bir bardak suya ihtiyacım var.", partOfSpeech: "noun", phonetics: "/ˈwɔːtər/" },
      { english: "Food", turkish: "Yemek", example: "The food is delicious.", exampleTurkish: "Yemek çok lezzetli.", partOfSpeech: "noun", phonetics: "/fuːd/" },
      { english: "House", turkish: "Ev", example: "This is my house.", exampleTurkish: "Bu benim evim.", partOfSpeech: "noun", phonetics: "/haʊs/" },
      { english: "Car", turkish: "Araba", example: "The car is red.", exampleTurkish: "Araba kırmızı.", partOfSpeech: "noun", phonetics: "/kɑːr/" },
      { english: "Book", turkish: "Kitap", example: "I am reading a book.", exampleTurkish: "Bir kitap okuyorum.", partOfSpeech: "noun", phonetics: "/bʊk/" },
      { english: "Friend", turkish: "Arkadaş", example: "She is my best friend.", exampleTurkish: "O benim en iyi arkadaşım.", partOfSpeech: "noun", phonetics: "/frɛnd/" },
      { english: "Family", turkish: "Aile", example: "My family is big.", exampleTurkish: "Ailem büyük.", partOfSpeech: "noun", phonetics: "/ˈfæməli/" },
      { english: "School", turkish: "Okul", example: "I go to school every day.", exampleTurkish: "Her gün okula giderim.", partOfSpeech: "noun", phonetics: "/skuːl/" },
      { english: "Teacher", turkish: "Öğretmen", example: "The teacher is kind.", exampleTurkish: "Öğretmen nazik.", partOfSpeech: "noun", phonetics: "/ˈtiːtʃər/" },
      { english: "Student", turkish: "Öğrenci", example: "I am a student.", exampleTurkish: "Ben bir öğrenciyim.", partOfSpeech: "noun", phonetics: "/ˈstjuːdənt/" },
      { english: "Big", turkish: "Büyük", example: "The house is very big.", exampleTurkish: "Ev çok büyük.", partOfSpeech: "adjective", phonetics: "/bɪɡ/" },
      { english: "Small", turkish: "Küçük", example: "The cat is small.", exampleTurkish: "Kedi küçük.", partOfSpeech: "adjective", phonetics: "/smɔːl/" },
      { english: "Good", turkish: "İyi", example: "This is a good book.", exampleTurkish: "Bu iyi bir kitap.", partOfSpeech: "adjective", phonetics: "/ɡʊd/" },
      { english: "Bad", turkish: "Kötü", example: "The weather is bad today.", exampleTurkish: "Bugün hava kötü.", partOfSpeech: "adjective", phonetics: "/bæd/" },
      { english: "Happy", turkish: "Mutlu", example: "I am very happy.", exampleTurkish: "Çok mutluyum.", partOfSpeech: "adjective", phonetics: "/ˈhæpi/" },
      { english: "Sad", turkish: "Üzgün", example: "She looks sad.", exampleTurkish: "O üzgün görünüyor.", partOfSpeech: "adjective", phonetics: "/sæd/" },
      { english: "Beautiful", turkish: "Güzel", example: "The flower is beautiful.", exampleTurkish: "Çiçek çok güzel.", partOfSpeech: "adjective", phonetics: "/ˈbjuːtɪfəl/" },
      { english: "New", turkish: "Yeni", example: "I have a new phone.", exampleTurkish: "Yeni bir telefonum var.", partOfSpeech: "adjective", phonetics: "/njuː/" },
      { english: "Old", turkish: "Eski", example: "This is an old house.", exampleTurkish: "Bu eski bir ev.", partOfSpeech: "adjective", phonetics: "/oʊld/" },
      { english: "Hot", turkish: "Sıcak", example: "The coffee is hot.", exampleTurkish: "Kahve sıcak.", partOfSpeech: "adjective", phonetics: "/hɒt/" },
      { english: "Cold", turkish: "Soğuk", example: "The water is cold.", exampleTurkish: "Su soğuk.", partOfSpeech: "adjective", phonetics: "/koʊld/" },
      { english: "Eat", turkish: "Yemek yemek", example: "I eat breakfast at 7.", exampleTurkish: "Saat 7'de kahvaltı yerim.", partOfSpeech: "verb", phonetics: "/iːt/" },
      { english: "Drink", turkish: "İçmek", example: "I drink water every day.", exampleTurkish: "Her gün su içerim.", partOfSpeech: "verb", phonetics: "/drɪŋk/" },
      { english: "Sleep", turkish: "Uyumak", example: "I sleep at night.", exampleTurkish: "Gece uyurum.", partOfSpeech: "verb", phonetics: "/sliːp/" },
      { english: "Walk", turkish: "Yürümek", example: "I walk to school.", exampleTurkish: "Okula yürüyorum.", partOfSpeech: "verb", phonetics: "/wɔːk/" },
      { english: "Run", turkish: "Koşmak", example: "I run every morning.", exampleTurkish: "Her sabah koşarım.", partOfSpeech: "verb", phonetics: "/rʌn/" },
      { english: "Read", turkish: "Okumak", example: "I read books at night.", exampleTurkish: "Gece kitap okurum.", partOfSpeech: "verb", phonetics: "/riːd/" },
      { english: "Write", turkish: "Yazmak", example: "I write in my diary.", exampleTurkish: "Günlüğüme yazarım.", partOfSpeech: "verb", phonetics: "/raɪt/" },
      { english: "Speak", turkish: "Konuşmak", example: "I speak English.", exampleTurkish: "İngilizce konuşuyorum.", partOfSpeech: "verb", phonetics: "/spiːk/" },
      { english: "Listen", turkish: "Dinlemek", example: "I listen to music.", exampleTurkish: "Müzik dinlerim.", partOfSpeech: "verb", phonetics: "/ˈlɪsən/" },
      { english: "Red", turkish: "Kırmızı", example: "The apple is red.", exampleTurkish: "Elma kırmızı.", partOfSpeech: "adjective", phonetics: "/rɛd/" },
      { english: "Blue", turkish: "Mavi", example: "The sky is blue.", exampleTurkish: "Gök mavi.", partOfSpeech: "adjective", phonetics: "/bluː/" },
      { english: "Green", turkish: "Yeşil", example: "The grass is green.", exampleTurkish: "Çimen yeşil.", partOfSpeech: "adjective", phonetics: "/ɡriːn/" },
      { english: "White", turkish: "Beyaz", example: "The snow is white.", exampleTurkish: "Kar beyaz.", partOfSpeech: "adjective", phonetics: "/waɪt/" },
      { english: "Black", turkish: "Siyah", example: "The night is black.", exampleTurkish: "Gece siyah.", partOfSpeech: "adjective", phonetics: "/blæk/" },
      { english: "Cat", turkish: "Kedi", example: "The cat is sleeping.", exampleTurkish: "Kedi uyuyor.", partOfSpeech: "noun", phonetics: "/kæt/" },
      { english: "Dog", turkish: "Köpek", example: "The dog is friendly.", exampleTurkish: "Köpek arkadaş canlısı.", partOfSpeech: "noun", phonetics: "/dɒɡ/" },
      { english: "Bird", turkish: "Kuş", example: "The bird is flying.", exampleTurkish: "Kuş uçuyor.", partOfSpeech: "noun", phonetics: "/bɜːrd/" },
      { english: "Tree", turkish: "Ağaç", example: "The tree is tall.", exampleTurkish: "Ağaç uzun.", partOfSpeech: "noun", phonetics: "/triː/" },
      { english: "Flower", turkish: "Çiçek", example: "The flower is pink.", exampleTurkish: "Çiçek pembe.", partOfSpeech: "noun", phonetics: "/ˈflaʊər/" },
      { english: "Sun", turkish: "Güneş", example: "The sun is bright.", exampleTurkish: "Güneş parlak.", partOfSpeech: "noun", phonetics: "/sʌn/" },
      { english: "Moon", turkish: "Ay", example: "The moon is full.", exampleTurkish: "Ay dolun.", partOfSpeech: "noun", phonetics: "/muːn/" },
      { english: "Star", turkish: "Yıldız", example: "The stars are beautiful.", exampleTurkish: "Yıldızlar güzel.", partOfSpeech: "noun", phonetics: "/stɑːr/" },
      { english: "Rain", turkish: "Yağmur", example: "It is raining.", exampleTurkish: "Yağmur yağıyor.", partOfSpeech: "noun", phonetics: "/reɪn/" },
      { english: "Snow", turkish: "Kar", example: "The snow is white.", exampleTurkish: "Kar beyaz.", partOfSpeech: "noun", phonetics: "/snoʊ/" },
      { english: "Door", turkish: "Kapı", example: "Please close the door.", exampleTurkish: "Lütfen kapıyı kapatın.", partOfSpeech: "noun", phonetics: "/dɔːr/" },
      { english: "Window", turkish: "Pencere", example: "Open the window.", exampleTurkish: "Pencereyi aç.", partOfSpeech: "noun", phonetics: "/ˈwɪndoʊ/" },
      { english: "Table", turkish: "Masa", example: "The book is on the table.", exampleTurkish: "Kitap masada.", partOfSpeech: "noun", phonetics: "/ˈteɪbəl/" },
      { english: "Chair", turkish: "Sandalye", example: "Sit on the chair.", exampleTurkish: "Sandalyeye otur.", partOfSpeech: "noun", phonetics: "/tʃɛr/" },
      { english: "Like", turkish: "Beğenmek", example: "I like chocolate.", exampleTurkish: "Çikolatayı severim.", partOfSpeech: "verb", phonetics: "/laɪk/" },
      { english: "Love", turkish: "Sevmek", example: "I love my family.", exampleTurkish: "Ailemi severim.", partOfSpeech: "verb", phonetics: "/lʌv/" },
      { english: "Want", turkish: "İstemek", example: "I want water.", exampleTurkish: "Su istiyorum.", partOfSpeech: "verb", phonetics: "/wɒnt/" },
      { english: "Need", turkish: "İhtiyaç duymak", example: "I need help.", exampleTurkish: "Yardıma ihtiyacım var.", partOfSpeech: "verb", phonetics: "/niːd/" },
      { english: "Go", turkish: "Gitmek", example: "I go to school.", exampleTurkish: "Okula giderim.", partOfSpeech: "verb", phonetics: "/ɡoʊ/" },
      { english: "Come", turkish: "Gelmek", example: "Come here, please.", exampleTurkish: "Lütfen buraya gel.", partOfSpeech: "verb", phonetics: "/kʌm/" },
      { english: "See", turkish: "Görmek", example: "I can see the mountain.", exampleTurkish: "Dağı görebiliyorum.", partOfSpeech: "verb", phonetics: "/siː/" },
      { english: "Make", turkish: "Yapmak", example: "I make breakfast.", exampleTurkish: "Kahvaltı hazırlarım.", partOfSpeech: "verb", phonetics: "/meɪk/" },
      { english: "Give", turkish: "Vermek", example: "Give me the book.", exampleTurkish: "Bana kitabı ver.", partOfSpeech: "verb", phonetics: "/ɡɪv/" },
      { english: "Take", turkish: "Almak", example: "Take this gift.", exampleTurkish: "Bu hediyeyi al.", partOfSpeech: "verb", phonetics: "/teɪk/" },
      { english: "Time", turkish: "Zaman", example: "What time is it?", exampleTurkish: "Saat kaç?", partOfSpeech: "noun", phonetics: "/taɪm/" },
      { english: "Day", turkish: "Gün", example: "Today is a good day.", exampleTurkish: "Bugün iyi bir gün.", partOfSpeech: "noun", phonetics: "/deɪ/" },
      { english: "What", turkish: "Ne", example: "What is your name?", exampleTurkish: "Adın ne?", partOfSpeech: "pronoun", phonetics: "/wɒt/" },
      { english: "Where", turkish: "Nerede", example: "Where is the bathroom?", exampleTurkish: "Banyo nerede?", partOfSpeech: "adverb", phonetics: "/wɛr/" },
      { english: "When", turkish: "Ne zaman", example: "When is your birthday?", exampleTurkish: "Doğum günün ne zaman?", partOfSpeech: "adverb", phonetics: "/wɛn/" },
      { english: "Why", turkish: "Neden", example: "Why are you sad?", exampleTurkish: "Neden üzgünsün?", partOfSpeech: "adverb", phonetics: "/waɪ/" },
      { english: "How", turkish: "Nasıl", example: "How are you?", exampleTurkish: "Nasılsın?", partOfSpeech: "adverb", phonetics: "/haʊ/" },
      { english: "Morning", turkish: "Sabah", example: "Good morning!", exampleTurkish: "Günaydın!", partOfSpeech: "noun", phonetics: "/ˈmɔːrnɪŋ/" },
      { english: "Night", turkish: "Gece", example: "Good night!", exampleTurkish: "İyi geceler!", partOfSpeech: "noun", phonetics: "/naɪt/" },
      { english: "Apple", turkish: "Elma", example: "I eat an apple.", exampleTurkish: "Bir elma yerim.", partOfSpeech: "noun", phonetics: "/ˈæpəl/" },
      { english: "Milk", turkish: "Süt", example: "I drink milk.", exampleTurkish: "Süt içerim.", partOfSpeech: "noun", phonetics: "/mɪlk/" },
      { english: "Bread", turkish: "Ekmek", example: "I eat bread for breakfast.", exampleTurkish: "Kahvaltıda ekmek yerim.", partOfSpeech: "noun", phonetics: "/brɛd/" },
      { english: "Work", turkish: "Çalışmak", example: "I work in an office.", exampleTurkish: "Ofiste çalışırım.", partOfSpeech: "verb", phonetics: "/wɜːrk/" },
      { english: "Help", turkish: "Yardım", example: "I need your help.", exampleTurkish: "Yardımına ihtiyacım var.", partOfSpeech: "noun", phonetics: "/hɛlp/" },
      { english: "Here", turkish: "Burada", example: "I am here.", exampleTurkish: "Ben buradayım.", partOfSpeech: "adverb", phonetics: "/hɪr/" },
      { english: "There", turkish: "Orada", example: "The book is there.", exampleTurkish: "Kitap orada.", partOfSpeech: "adverb", phonetics: "/ðɛr/" },
      { english: "This", turkish: "Bu", example: "This is my book.", exampleTurkish: "Bu benim kitabım.", partOfSpeech: "pronoun", phonetics: "/ðɪs/" },
      { english: "That", turkish: "Şu", example: "That is a nice car.", exampleTurkish: "Şu güzel bir araba.", partOfSpeech: "pronoun", phonetics: "/ðæt/" },
      { english: "Who", turkish: "Kim", example: "Who is that person?", exampleTurkish: "O kişi kim?", partOfSpeech: "pronoun", phonetics: "/huː/" },
      { english: "Which", turkish: "Hangi", example: "Which color do you like?", exampleTurkish: "Hangi rengi seversin?", partOfSpeech: "pronoun", phonetics: "/wɪtʃ/" },
      { english: "Always", turkish: "Her zaman", example: "I always wake up early.", exampleTurkish: "Her zaman erken kalkarım.", partOfSpeech: "adverb", phonetics: "/ˈɔːlweɪz/" },
      { english: "Never", turkish: "Asla", example: "I never eat fish.", exampleTurkish: "Asla balık yemem.", partOfSpeech: "adverb", phonetics: "/ˈnɛvər/" },
      { english: "Sometimes", turkish: "Bazen", example: "I sometimes go shopping.", exampleTurkish: "Bazen alışverişe giderim.", partOfSpeech: "adverb", phonetics: "/ˈsʌmtaɪmz/" },
      { english: "Very", turkish: "Çok", example: "It is very cold.", exampleTurkish: "Çok soğuk.", partOfSpeech: "adverb", phonetics: "/ˈvɛri/" },
      { english: "Now", turkish: "Şimdi", example: "I am busy now.", exampleTurkish: "Şu an meşgulüm.", partOfSpeech: "adverb", phonetics: "/naʊ/" },
      { english: "One", turkish: "Bir", example: "I have one cat.", exampleTurkish: "Bir kedim var.", partOfSpeech: "noun", phonetics: "/wʌn/" },
      { english: "Two", turkish: "İki", example: "I have two brothers.", exampleTurkish: "İki erkek kardeşim var.", partOfSpeech: "noun", phonetics: "/tuː/" },
      { english: "Three", turkish: "Üç", example: "There are three books.", exampleTurkish: "Üç kitap var.", partOfSpeech: "noun", phonetics: "/θriː/" },
      { english: "Monday", turkish: "Pazartesi", example: "Monday is the first day.", exampleTurkish: "Pazartesi ilk gündür.", partOfSpeech: "noun", phonetics: "/ˈmʌndeɪ/" },
      { english: "Today", turkish: "Bugün", example: "Today is Monday.", exampleTurkish: "Bugün pazartesi.", partOfSpeech: "adverb", phonetics: "/təˈdeɪ/" },
      { english: "Tomorrow", turkish: "Yarın", example: "See you tomorrow.", exampleTurkish: "Yarın görüşürüz.", partOfSpeech: "adverb", phonetics: "/təˈmɒroʊ/" },
      { english: "Yesterday", turkish: "Dün", example: "Yesterday was Sunday.", exampleTurkish: "Dün pazardı.", partOfSpeech: "adverb", phonetics: "/ˈjɛstərdeɪ/" },
      { english: "Life", turkish: "Hayat", example: "Life is short.", exampleTurkish: "Hayat kısa.", partOfSpeech: "noun", phonetics: "/laɪf/" },
      { english: "World", turkish: "Dünya", example: "The world is beautiful.", exampleTurkish: "Dünya güzel.", partOfSpeech: "noun", phonetics: "/wɜːrld/" },
      { english: "Hand", turkish: "El", example: "Give me your hand.", exampleTurkish: "Elini ver.", partOfSpeech: "noun", phonetics: "/hænd/" },
      { english: "Eye", turkish: "Göz", example: "She has blue eyes.", exampleTurkish: "Mavi gözleri var.", partOfSpeech: "noun", phonetics: "/aɪ/" },
      { english: "Head", turkish: "Kafa", example: "I have a headache.", exampleTurkish: "Başım ağrıyor.", partOfSpeech: "noun", phonetics: "/hɛd/" },
      { english: "Heart", turkish: "Kalp", example: "My heart is happy.", exampleTurkish: "Kalbim mutlu.", partOfSpeech: "noun", phonetics: "/hɑːrt/" },
      { english: "Face", turkish: "Yüz", example: "Wash your face.", exampleTurkish: "Yüzünü yıka.", partOfSpeech: "noun", phonetics: "/feɪs/" },
      { english: "Strong", turkish: "Güçlü", example: "He is very strong.", exampleTurkish: "O çok güçlü.", partOfSpeech: "adjective", phonetics: "/strɒŋ/" },
      { english: "Fast", turkish: "Hızlı", example: "The car is very fast.", exampleTurkish: "Araba çok hızlı.", partOfSpeech: "adjective", phonetics: "/fæst/" },
      { english: "Slow", turkish: "Yavaş", example: "The turtle is slow.", exampleTurkish: "Kaplumbağa yavaş.", partOfSpeech: "adjective", phonetics: "/sloʊ/" },
      { english: "Easy", turkish: "Kolay", example: "This task is easy.", exampleTurkish: "Bu görev kolay.", partOfSpeech: "adjective", phonetics: "/ˈiːzi/" },
      { english: "Difficult", turkish: "Zor", example: "The exam is difficult.", exampleTurkish: "Sınav zor.", partOfSpeech: "adjective", phonetics: "/ˈdɪfɪkəlt/" },
      { english: "Clean", turkish: "Temiz", example: "Keep your room clean.", exampleTurkish: "Odanı temiz tut.", partOfSpeech: "adjective", phonetics: "/kliːn/" },
      { english: "Dirty", turkish: "Kirli", example: "Your shoes are dirty.", exampleTurkish: "Ayakkabıların kirli.", partOfSpeech: "adjective", phonetics: "/ˈdɜːrti/" },
      { english: "Full", turkish: "Dolu", example: "The glass is full.", exampleTurkish: "Bardak dolu.", partOfSpeech: "adjective", phonetics: "/fʊl/" },
      { english: "Empty", turkish: "Boş", example: "The box is empty.", exampleTurkish: "Kutu boş.", partOfSpeech: "adjective", phonetics: "/ˈɛmpti/" },
      { english: "Play", turkish: "Oynamak", example: "Children play in the park.", exampleTurkish: "Çocuklar parkta oynar.", partOfSpeech: "verb", phonetics: "/pleɪ/" },
      { english: "Cook", turkish: "Yemek pişirmek", example: "I like to cook.", exampleTurkish: "Yemek pişirmeyi severim.", partOfSpeech: "verb", phonetics: "/kʊk/" },
      { english: "Wash", turkish: "Yıkamak", example: "Wash your hands.", exampleTurkish: "Ellerini yıka.", partOfSpeech: "verb", phonetics: "/wɒʃ/" },
      { english: "Call", turkish: "Aramak", example: "I will call you later.", exampleTurkish: "Daha sonra seni ararım.", partOfSpeech: "verb", phonetics: "/kɔːl/" },
      { english: "Wait", turkish: "Beklemek", example: "Please wait here.", exampleTurkish: "Lütfen burada bekle.", partOfSpeech: "verb", phonetics: "/weɪt/" },
      { english: "Move", turkish: "Hareket etmek", example: "I want to move.", exampleTurkish: "Taşınmak istiyorum.", partOfSpeech: "verb", phonetics: "/muːv/" },
      { english: "Live", turkish: "Yaşamak", example: "I live in Istanbul.", exampleTurkish: "İstanbul'da yaşıyorum.", partOfSpeech: "verb", phonetics: "/lɪv/" },
      { english: "Change", turkish: "Değiştirmek", example: "I want to change.", exampleTurkish: "Değişmek istiyorum.", partOfSpeech: "verb", phonetics: "/tʃeɪndʒ/" },
      { english: "Find", turkish: "Bulmak", example: "I can't find my keys.", exampleTurkish: "Anahtarlarımı bulamıyorum.", partOfSpeech: "verb", phonetics: "/faɪnd/" },
      { english: "Try", turkish: "Denemek", example: "Try this food.", exampleTurkish: "Bu yemeği dene.", partOfSpeech: "verb", phonetics: "/traɪ/" },
      { english: "Start", turkish: "Başlamak", example: "Let's start the lesson.", exampleTurkish: "Dersi başlatalım.", partOfSpeech: "verb", phonetics: "/stɑːrt/" },
      { english: "Finish", turkish: "Bitirmek", example: "I finished my homework.", exampleTurkish: "Ödevimi bitirdim.", partOfSpeech: "verb", phonetics: "/ˈfɪnɪʃ/" },
      { english: "Think", turkish: "Düşünmek", example: "I think so.", exampleTurkish: "Öyle düşünüyorum.", partOfSpeech: "verb", phonetics: "/θɪŋk/" },
      { english: "Know", turkish: "Bilmek", example: "I know the answer.", exampleTurkish: "Cevabı biliyorum.", partOfSpeech: "verb", phonetics: "/noʊ/" },
      { english: "Understand", turkish: "Anlamak", example: "I understand English.", exampleTurkish: "İngilizce anlıyorum.", partOfSpeech: "verb", phonetics: "/ˌʌndərˈstænd/" },
      { english: "Remember", turkish: "Hatırlamak", example: "I remember your name.", exampleTurkish: "Adını hatırlıyorum.", partOfSpeech: "verb", phonetics: "/rɪˈmɛmbər/" },
      { english: "Forget", turkish: "Unutmak", example: "Don't forget your keys.", exampleTurkish: "Anahtarlarını unutma.", partOfSpeech: "verb", phonetics: "/fərˈɡɛt/" },
      { english: "Feel", turkish: "Hissetmek", example: "I feel happy.", exampleTurkish: "Mutlu hissediyorum.", partOfSpeech: "verb", phonetics: "/fiːl/" },
      { english: "Music", turkish: "Müzik", example: "I love music.", exampleTurkish: "Müziği severim.", partOfSpeech: "noun", phonetics: "/ˈmjuːzɪk/" },
      { english: "Money", turkish: "Para", example: "I don't have money.", exampleTurkish: "Param yok.", partOfSpeech: "noun", phonetics: "/ˈmʌni/" },
      { english: "Job", turkish: "İş", example: "I have a new job.", exampleTurkish: "Yeni bir işim var.", partOfSpeech: "noun", phonetics: "/dʒɒb/" },
      { english: "Room", turkish: "Oda", example: "My room is clean.", exampleTurkish: "Odam temiz.", partOfSpeech: "noun", phonetics: "/ruːm/" },
      { english: "Before", turkish: "Önce", example: "Wash hands before eating.", exampleTurkish: "Yemeden önce ellerini yıka.", partOfSpeech: "preposition", phonetics: "/bɪˈfɔːr/" },
      { english: "After", turkish: "Sonra", example: "After school, I play.", exampleTurkish: "Okuldan sonra oynarım.", partOfSpeech: "preposition", phonetics: "/ˈæftər/" },
      { english: "With", turkish: "İle", example: "I go with my friend.", exampleTurkish: "Arkadaşımla giderim.", partOfSpeech: "preposition", phonetics: "/wɪð/" },
      { english: "From", turkish: "Dan", example: "I am from Turkey.", exampleTurkish: "Ben Türkiye'denim.", partOfSpeech: "preposition", phonetics: "/frɒm/" },
      { english: "For", turkish: "İçin", example: "This is for you.", exampleTurkish: "Bu senin için.", partOfSpeech: "preposition", phonetics: "/fɔːr/" },
      { english: "About", turkish: "Hakkında", example: "Tell me about yourself.", exampleTurkish: "Kendinden bahset.", partOfSpeech: "preposition", phonetics: "/əˈbaʊt/" },
      { english: "Open", turkish: "Aç", example: "Open the door.", exampleTurkish: "Kapıyı aç.", partOfSpeech: "verb", phonetics: "/ˈoʊpən/" },
      { english: "Close", turkish: "Kapat", example: "Close the window.", exampleTurkish: "Pencereyi kapat.", partOfSpeech: "verb", phonetics: "/kloʊz/" },
      { english: "Buy", turkish: "Satın almak", example: "I want to buy a car.", exampleTurkish: "Araba satın almak istiyorum.", partOfSpeech: "verb", phonetics: "/baɪ/" },
      { english: "Sell", turkish: "Satmak", example: "He sells vegetables.", exampleTurkish: "O sebze satar.", partOfSpeech: "verb", phonetics: "/sɛl/" },
      { english: "Answer", turkish: "Cevap vermek", example: "Please answer the phone.", exampleTurkish: "Lütfen telefona cevap ver.", partOfSpeech: "verb", phonetics: "/ˈænsər/" },
      { english: "Ask", turkish: "Sormak", example: "Can I ask you something?", exampleTurkish: "Sana bir şey sorabilir miyim?", partOfSpeech: "verb", phonetics: "/æsk/" },
      { english: "Tell", turkish: "Söylemek", example: "Tell me the truth.", exampleTurkish: "Bana gerçeği söyle.", partOfSpeech: "verb", phonetics: "/tɛl/" },
      { english: "Learn", turkish: "Öğrenmek", example: "I want to learn English.", exampleTurkish: "İngilizce öğrenmek istiyorum.", partOfSpeech: "verb", phonetics: "/lɜːrn/" },
      { english: "Teach", turkish: "Öğretmek", example: "I teach English.", exampleTurkish: "İngilizce öğretirim.", partOfSpeech: "verb", phonetics: "/tiːtʃ/" },
      { english: "Study", turkish: "Çalışmak", example: "I study every day.", exampleTurkish: "Her gün çalışırım.", partOfSpeech: "verb", phonetics: "/ˈstʌdi/" },
      { english: "Enjoy", turkish: "Zevk almak", example: "I enjoy reading.", exampleTurkish: "Okumaktan zevk alırım.", partOfSpeech: "verb", phonetics: "/ɪnˈdʒɔɪ/" },
      { english: "Hope", turkish: "Umak", example: "I hope you are well.", exampleTurkish: "İyi olmanı umuyorum.", partOfSpeech: "verb", phonetics: "/hoʊp/" },
      { english: "Believe", turkish: "İnanmak", example: "I believe you.", exampleTurkish: "Sana inanıyorum.", partOfSpeech: "verb", phonetics: "/bɪˈliːv/" },
      { english: "Carry", turkish: "Taşımak", example: "I carry my bag.", exampleTurkish: "Çantamı taşırım.", partOfSpeech: "verb", phonetics: "/ˈkæri/" },
      { english: "Bring", turkish: "Getirmek", example: "Bring me some water.", exampleTurkish: "Bana su getir.", partOfSpeech: "verb", phonetics: "/brɪŋ/" },
      { english: "Send", turkish: "Göndermek", example: "I will send an email.", exampleTurkish: "E-posta göndereceğim.", partOfSpeech: "verb", phonetics: "/sɛnd/" },
      { english: "Sing", turkish: "Şarkı söylemek", example: "She sings beautifully.", exampleTurkish: "Güzel şarkı söyler.", partOfSpeech: "verb", phonetics: "/sɪŋ/" },
      { english: "Dance", turkish: "Dans etmek", example: "I love to dance.", exampleTurkish: "Dans etmeyi severim.", partOfSpeech: "verb", phonetics: "/dæns/" },
      { english: "Travel", turkish: "Seyahat etmek", example: "I love to travel.", exampleTurkish: "Seyahat etmeyi severim.", partOfSpeech: "verb", phonetics: "/ˈtrævəl/" },
      { english: "Visit", turkish: "Ziyaret etmek", example: "I visit my grandparents.", exampleTurkish: "Büyükannemi ve büyükbabamı ziyaret ederim.", partOfSpeech: "verb", phonetics: "/ˈvɪzɪt/" },
      { english: "Follow", turkish: "Takip etmek", example: "Follow me.", exampleTurkish: "Beni takip et.", partOfSpeech: "verb", phonetics: "/ˈfɒloʊ/" },
      { english: "Draw", turkish: "Çizmek", example: "I like to draw.", exampleTurkish: "Çizmeyi severim.", partOfSpeech: "verb", phonetics: "/drɔː/" },
      { english: "Fix", turkish: "Tamir etmek", example: "Can you fix this?", exampleTurkish: "Bunu tamir edebilir misin?", partOfSpeech: "verb", phonetics: "/fɪks/" },
      { english: "Push", turkish: "İtmek", example: "Push the door.", exampleTurkish: "Kapıyı it.", partOfSpeech: "verb", phonetics: "/pʊʃ/" },
      { english: "Pull", turkish: "Çekmek", example: "Pull the rope.", exampleTurkish: "İpi çek.", partOfSpeech: "verb", phonetics: "/pʊl/" },
      { english: "Cut", turkish: "Kesmek", example: "Cut the paper.", exampleTurkish: "Kağıdı kes.", partOfSpeech: "verb", phonetics: "/kʌt/" },
      { english: "Throw", turkish: "Atmak", example: "Throw the ball.", exampleTurkish: "Topu at.", partOfSpeech: "verb", phonetics: "/θroʊ/" },
      { english: "Catch", turkish: "Tutmak", example: "Catch the ball.", exampleTurkish: "Topu tut.", partOfSpeech: "verb", phonetics: "/kætʃ/" },
      { english: "Break", turkish: "Kırmak", example: "Don't break the glass.", exampleTurkish: "Camı kırmayın.", partOfSpeech: "verb", phonetics: "/breɪk/" },
      { english: "Put", turkish: "Koymak", example: "Put the book on the table.", exampleTurkish: "Kitabı masaya koy.", partOfSpeech: "verb", phonetics: "/pʊt/" },
      { english: "Keep", turkish: "Tutmak", example: "Keep your room clean.", exampleTurkish: "Odanı temiz tut.", partOfSpeech: "verb", phonetics: "/kiːp/" },
      { english: "Let", turkish: "İzin vermek", example: "Let me help you.", exampleTurkish: "İzin ver yardım edeyim.", partOfSpeech: "verb", phonetics: "/lɛt/" },
      { english: "Begin", turkish: "Başlamak", example: "The class begins at 9.", exampleTurkish: "Ders saat 9'da başlar.", partOfSpeech: "verb", phonetics: "/bɪˈɡɪn/" },
      { english: "Hear", turkish: "Duymak", example: "I can hear music.", exampleTurkish: "Müzik duyabiliyorum.", partOfSpeech: "verb", phonetics: "/hɪr/" },
      { english: "Worry", turkish: "Endişelenmek", example: "Don't worry about me.", exampleTurkish: "Benim için endişelenme.", partOfSpeech: "verb", phonetics: "/ˈwɜːri/" },
      { english: "Plan", turkish: "Plan", example: "What is your plan?", exampleTurkish: "Planın ne?", partOfSpeech: "noun", phonetics: "/plæn/" },
      { english: "Problem", turkish: "Sorun", example: "What is the problem?", exampleTurkish: "Sorun ne?", partOfSpeech: "noun", phonetics: "/ˈprɒbləm/" },
      { english: "Question", turkish: "Soru", example: "I have a question.", exampleTurkish: "Bir sorum var.", partOfSpeech: "noun", phonetics: "/ˈkwɛstʃən/" },
      { english: "Game", turkish: "Oyun", example: "Let's play a game.", exampleTurkish: "Bir oyun oynayalım.", partOfSpeech: "noun", phonetics: "/ɡeɪm/" },
      { english: "Movie", turkish: "Film", example: "Let's watch a movie.", exampleTurkish: "Bir film izleyelim.", partOfSpeech: "noun", phonetics: "/ˈmuːvi/" },
      { english: "Color", turkish: "Renk", example: "What is your favorite color?", exampleTurkish: "En sevdiğin renk ne?", partOfSpeech: "noun", phonetics: "/ˈkʌlər/" },
      { english: "Place", turkish: "Yer", example: "This is a beautiful place.", exampleTurkish: "Bu güzel bir yer.", partOfSpeech: "noun", phonetics: "/pleɪs/" },
      { english: "Thing", turkish: "Şey", example: "What is this thing?", exampleTurkish: "Bu şey ne?", partOfSpeech: "noun", phonetics: "/θɪŋ/" },
      { english: "Idea", turkish: "Fikir", example: "That's a great idea.", exampleTurkish: "Bu harika bir fikir.", partOfSpeech: "noun", phonetics: "/aɪˈdɪə/" },
      { english: "Story", turkish: "Hikaye", example: "Tell me a story.", exampleTurkish: "Bana bir hikaye anlat.", partOfSpeech: "noun", phonetics: "/ˈstɔːri/" },
      { english: "Voice", turkish: "Ses", example: "I recognize your voice.", exampleTurkish: "Sesini tanıyorum.", partOfSpeech: "noun", phonetics: "/vɔɪs/" },
      { english: "Body", turkish: "Vücut", example: "The human body is amazing.", exampleTurkish: "İnsan vücudu harika.", partOfSpeech: "noun", phonetics: "/ˈbɒdi/" },
    ]
  },
  {
    name: "A2 - Temel",
    description: "Günlük yaşamda sık kullanılan kelimeler",
    color: "#2196F3",
    icon: "📘",
    words: [
      { english: "Adventure", turkish: "Macera", example: "We went on an adventure.", exampleTurkish: "Bir maceraya çıktık.", partOfSpeech: "noun", phonetics: "/ədˈvɛntʃər/" },
      { english: "Advice", turkish: "Tavsiye", example: "She gave me good advice.", exampleTurkish: "Bana iyi tavsiye verdi.", partOfSpeech: "noun", phonetics: "/ədˈvaɪs/" },
      { english: "Agreement", turkish: "Anlaşma", example: "We reached an agreement.", exampleTurkish: "Bir anlaşmaya vardık.", partOfSpeech: "noun", phonetics: "/əˈɡriːmənt/" },
      { english: "Apartment", turkish: "Daire", example: "I live in a small apartment.", exampleTurkish: "Küçük bir dairede yaşıyorum.", partOfSpeech: "noun", phonetics: "/əˈpɑːrtmənt/" },
      { english: "Attention", turkish: "Dikkat", example: "Pay attention to me.", exampleTurkish: "Bana dikkat et.", partOfSpeech: "noun", phonetics: "/əˈtɛnʃən/" },
      { english: "Balance", turkish: "Denge", example: "You need balance in life.", exampleTurkish: "Hayatta dengeye ihtiyacın var.", partOfSpeech: "noun", phonetics: "/ˈbæləns/" },
      { english: "Behavior", turkish: "Davranış", example: "Good behavior is important.", exampleTurkish: "İyi davranış önemlidir.", partOfSpeech: "noun", phonetics: "/bɪˈheɪvjər/" },
      { english: "Belief", turkish: "İnanç", example: "This is my belief.", exampleTurkish: "Bu benim inancım.", partOfSpeech: "noun", phonetics: "/bɪˈliːf/" },
      { english: "Career", turkish: "Kariyer", example: "She has a great career.", exampleTurkish: "Harika bir kariyeri var.", partOfSpeech: "noun", phonetics: "/kəˈrɪr/" },
      { english: "Choice", turkish: "Seçim", example: "You have a choice.", exampleTurkish: "Seçimin var.", partOfSpeech: "noun", phonetics: "/tʃɔɪs/" },
      { english: "Communication", turkish: "İletişim", example: "Communication is key.", exampleTurkish: "İletişim önemlidir.", partOfSpeech: "noun", phonetics: "/kəˌmjuːnɪˈkeɪʃən/" },
      { english: "Competition", turkish: "Yarışma", example: "The competition was fierce.", exampleTurkish: "Yarışma şiddetliydi.", partOfSpeech: "noun", phonetics: "/ˌkɒmpəˈtɪʃən/" },
      { english: "Confidence", turkish: "Özgüven", example: "She has confidence.", exampleTurkish: "Özgüveni var.", partOfSpeech: "noun", phonetics: "/ˈkɒnfɪdəns/" },
      { english: "Conversation", turkish: "Sohbet", example: "We had a nice conversation.", exampleTurkish: "Güzel bir sohbet ettik.", partOfSpeech: "noun", phonetics: "/ˌkɒnvərˈseɪʃən/" },
      { english: "Decision", turkish: "Karar", example: "I made a decision.", exampleTurkish: "Bir karar verdim.", partOfSpeech: "noun", phonetics: "/dɪˈsɪʒən/" },
      { english: "Description", turkish: "Tanım", example: "Give a description of the event.", exampleTurkish: "Etkinliğin tanımını ver.", partOfSpeech: "noun", phonetics: "/dɪˈskrɪpʃən/" },
      { english: "Distance", turkish: "Mesafe", example: "What is the distance?", exampleTurkish: "Mesafe ne kadar?", partOfSpeech: "noun", phonetics: "/ˈdɪstəns/" },
      { english: "Education", turkish: "Eğitim", example: "Education is important.", exampleTurkish: "Eğitim önemlidir.", partOfSpeech: "noun", phonetics: "/ˌɛdʒʊˈkeɪʃən/" },
      { english: "Effort", turkish: "Çaba", example: "I made an effort.", exampleTurkish: "Bir çaba gösterdim.", partOfSpeech: "noun", phonetics: "/ˈɛfərt/" },
      { english: "Environment", turkish: "Çevre", example: "Protect the environment.", exampleTurkish: "Çevreyi koru.", partOfSpeech: "noun", phonetics: "/ɪnˈvaɪrənmənt/" },
      { english: "Equipment", turkish: "Ekipman", example: "We need new equipment.", exampleTurkish: "Yeni ekipmana ihtiyacımız var.", partOfSpeech: "noun", phonetics: "/ɪˈkwɪpmənt/" },
      { english: "Event", turkish: "Etkinlik", example: "The event was amazing.", exampleTurkish: "Etkinlik harikaydı.", partOfSpeech: "noun", phonetics: "/ɪˈvɛnt/" },
      { english: "Exercise", turkish: "Egzersiz", example: "I do exercise every day.", exampleTurkish: "Her gün egzersiz yaparım.", partOfSpeech: "noun", phonetics: "/ˈɛksərsaɪz/" },
      { english: "Fact", turkish: "Gerçek", example: "This is a fact.", exampleTurkish: "Bu bir gerçek.", partOfSpeech: "noun", phonetics: "/fækt/" },
      { english: "Freedom", turkish: "Özgürlük", example: "Freedom is important.", exampleTurkish: "Özgürlük önemlidir.", partOfSpeech: "noun", phonetics: "/ˈfriːdəm/" },
      { english: "Goal", turkish: "Hedef", example: "My goal is to succeed.", exampleTurkish: "Hedefim başarmak.", partOfSpeech: "noun", phonetics: "/ɡoʊl/" },
      { english: "Government", turkish: "Hükümet", example: "The government made a decision.", exampleTurkish: "Hükümet bir karar verdi.", partOfSpeech: "noun", phonetics: "/ˈɡʌvərnmənt/" },
      { english: "Guest", turkish: "Misafir", example: "We have a guest.", exampleTurkish: "Misafirimiz var.", partOfSpeech: "noun", phonetics: "/ɡɛst/" },
      { english: "Habit", turkish: "Alışkanlık", example: "Reading is a good habit.", exampleTurkish: "Okuma iyi bir alışkanlık.", partOfSpeech: "noun", phonetics: "/ˈhæbɪt/" },
      { english: "Happiness", turkish: "Mutluluk", example: "Happiness is important.", exampleTurkish: "Mutluluk önemlidir.", partOfSpeech: "noun", phonetics: "/ˈhæpinəs/" },
      { english: "Health", turkish: "Sağlık", example: "Health is wealth.", exampleTurkish: "Sağlık servettir.", partOfSpeech: "noun", phonetics: "/hɛlθ/" },
      { english: "History", turkish: "Tarih", example: "I love history.", exampleTurkish: "Tarihi severim.", partOfSpeech: "noun", phonetics: "/ˈhɪstəri/" },
      { english: "Hobby", turkish: "Hobi", example: "My hobby is painting.", exampleTurkish: "Hobim resim yapmak.", partOfSpeech: "noun", phonetics: "/ˈhɒbi/" },
      { english: "Humor", turkish: "Mizah", example: "He has a good sense of humor.", exampleTurkish: "İyi bir mizah anlayışı var.", partOfSpeech: "noun", phonetics: "/ˈhjuːmər/" },
      { english: "Importance", turkish: "Önem", example: "The importance of education.", exampleTurkish: "Eğitimin önemi.", partOfSpeech: "noun", phonetics: "/ɪmˈpɔːrtəns/" },
      { english: "Independence", turkish: "Bağımsızlık", example: "Independence is precious.", exampleTurkish: "Bağımsızlık değerlidir.", partOfSpeech: "noun", phonetics: "/ˌɪndɪˈpɛndəns/" },
      { english: "Influence", turkish: "Etki", example: "She has influence.", exampleTurkish: "Etkisi var.", partOfSpeech: "noun", phonetics: "/ˈɪnfluəns/" },
      { english: "Invention", turkish: "Buluş", example: "The invention of the wheel was important.", exampleTurkish: "Tekerleğin buluşu önemliydi.", partOfSpeech: "noun", phonetics: "/ɪnˈvɛnʃən/" },
      { english: "Journey", turkish: "Yolculuk", example: "The journey was long.", exampleTurkish: "Yolculuk uzundu.", partOfSpeech: "noun", phonetics: "/ˈdʒɜːrni/" },
      { english: "Knowledge", turkish: "Bilgi", example: "Knowledge is power.", exampleTurkish: "Bilgi güçtür.", partOfSpeech: "noun", phonetics: "/ˈnɒlɪdʒ/" },
      { english: "Law", turkish: "Yasa", example: "Obey the law.", exampleTurkish: "Yasaya uymalısın.", partOfSpeech: "noun", phonetics: "/lɔː/" },
      { english: "Leader", turkish: "Lider", example: "She is a great leader.", exampleTurkish: "Harika bir lider.", partOfSpeech: "noun", phonetics: "/ˈliːdər/" },
      { english: "Luck", turkish: "Şans", example: "Good luck!", exampleTurkish: "İyi şanslar!", partOfSpeech: "noun", phonetics: "/lʌk/" },
      { english: "Machine", turkish: "Makine", example: "The machine is broken.", exampleTurkish: "Makine bozuk.", partOfSpeech: "noun", phonetics: "/məˈʃiːn/" },
      { english: "Memory", turkish: "Hafıza", example: "I have a good memory.", exampleTurkish: "İyi bir hafızam var.", partOfSpeech: "noun", phonetics: "/ˈmɛməri/" },
      { english: "Method", turkish: "Yöntem", example: "What method do you use?", exampleTurkish: "Hangi yöntemi kullanıyorsun?", partOfSpeech: "noun", phonetics: "/ˈmɛθəd/" },
      { english: "Mind", turkish: "Zihin", example: "Change your mind.", exampleTurkish: "Fikrini değiştir.", partOfSpeech: "noun", phonetics: "/maɪnd/" },
      { english: "Mistake", turkish: "Hata", example: "I made a mistake.", exampleTurkish: "Bir hata yaptım.", partOfSpeech: "noun", phonetics: "/mɪˈsteɪk/" },
      { english: "Nature", turkish: "Doğa", example: "I love nature.", exampleTurkish: "Doğayı severim.", partOfSpeech: "noun", phonetics: "/ˈneɪtʃər/" },
      { english: "Opportunity", turkish: "Fırsat", example: "This is a great opportunity.", exampleTurkish: "Bu harika bir fırsat.", partOfSpeech: "noun", phonetics: "/ˌɒpərˈtjuːnɪti/" },
      { english: "Opinion", turkish: "Görüş", example: "What is your opinion?", exampleTurkish: "Görüşün ne?", partOfSpeech: "noun", phonetics: "/əˈpɪnjən/" },
      { english: "Peace", turkish: "Barış", example: "We want peace.", exampleTurkish: "Barış istiyoruz.", partOfSpeech: "noun", phonetics: "/piːs/" },
      { english: "Performance", turkish: "Performans", example: "Your performance was great.", exampleTurkish: "Performansın harikaydı.", partOfSpeech: "noun", phonetics: "/pərˈfɔːrməns/" },
      { english: "Permission", turkish: "İzin", example: "Can I have your permission?", exampleTurkish: "İzin verir misin?", partOfSpeech: "noun", phonetics: "/pərˈmɪʃən/" },
      { english: "Personality", turkish: "Kişilik", example: "She has a great personality.", exampleTurkish: "Harika bir kişiliği var.", partOfSpeech: "noun", phonetics: "/ˌpɜːrsəˈnælɪti/" },
      { english: "Pleasure", turkish: "Zevk", example: "It was my pleasure.", exampleTurkish: "Benim zevkimdi.", partOfSpeech: "noun", phonetics: "/ˈplɛʒər/" },
      { english: "Position", turkish: "Pozisyon", example: "What position do you hold?", exampleTurkish: "Hangi pozisyondasın?", partOfSpeech: "noun", phonetics: "/pəˈzɪʃən/" },
      { english: "Possibility", turkish: "İhtimal", example: "Is there a possibility?", exampleTurkish: "Bir ihtimal var mı?", partOfSpeech: "noun", phonetics: "/ˌpɒsəˈbɪlɪti/" },
      { english: "Power", turkish: "Güç", example: "Knowledge is power.", exampleTurkish: "Bilgi güçtür.", partOfSpeech: "noun", phonetics: "/ˈpaʊər/" },
      { english: "Priority", turkish: "Öncelik", example: "Safety is the priority.", exampleTurkish: "Güvenlik öncelik.", partOfSpeech: "noun", phonetics: "/praɪˈɒrɪti/" },
      { english: "Progress", turkish: "İlerleme", example: "I am making progress.", exampleTurkish: "İlerleme kaydediyorum.", partOfSpeech: "noun", phonetics: "/ˈprɒɡrɛs/" },
      { english: "Purpose", turkish: "Amaç", example: "What is the purpose?", exampleTurkish: "Amaç ne?", partOfSpeech: "noun", phonetics: "/ˈpɜːrpəs/" },
      { english: "Quality", turkish: "Kalite", example: "Quality is important.", exampleTurkish: "Kalite önemlidir.", partOfSpeech: "noun", phonetics: "/ˈkwɒlɪti/" },
      { english: "Reaction", turkish: "Tepki", example: "What was your reaction?", exampleTurkish: "Tepkin ne oldu?", partOfSpeech: "noun", phonetics: "/riˈækʃən/" },
      { english: "Relationship", turkish: "İlişki", example: "We have a good relationship.", exampleTurkish: "İyi bir ilişkimiz var.", partOfSpeech: "noun", phonetics: "/rɪˈleɪʃənʃɪp/" },
      { english: "Responsibility", turkish: "Sorumluluk", example: "It is your responsibility.", exampleTurkish: "Bu senin sorumluluğun.", partOfSpeech: "noun", phonetics: "/rɪˌspɒnsəˈbɪlɪti/" },
      { english: "Result", turkish: "Sonuç", example: "What is the result?", exampleTurkish: "Sonuç ne?", partOfSpeech: "noun", phonetics: "/rɪˈzʌlt/" },
      { english: "Risk", turkish: "Risk", example: "Don't take risks.", exampleTurkish: "Risk alma.", partOfSpeech: "noun", phonetics: "/rɪsk/" },
      { english: "Rule", turkish: "Kural", example: "Follow the rules.", exampleTurkish: "Kurallara uymalısın.", partOfSpeech: "noun", phonetics: "/ruːl/" },
      { english: "Safety", turkish: "Güvenlik", example: "Safety first.", exampleTurkish: "Güvenlik önce.", partOfSpeech: "noun", phonetics: "/ˈseɪfti/" },
      { english: "Schedule", turkish: "Program", example: "What is your schedule?", exampleTurkish: "Programın ne?", partOfSpeech: "noun", phonetics: "/ˈʃɛdjuːl/" },
      { english: "Science", turkish: "Bilim", example: "Science is fascinating.", exampleTurkish: "Bilim büyüleyici.", partOfSpeech: "noun", phonetics: "/ˈsaɪəns/" },
      { english: "Society", turkish: "Toplum", example: "Society is changing.", exampleTurkish: "Toplum değişiyor.", partOfSpeech: "noun", phonetics: "/səˈsaɪəti/" },
      { english: "Success", turkish: "Başarı", example: "Success comes with hard work.", exampleTurkish: "Başarı çalışmayla gelir.", partOfSpeech: "noun", phonetics: "/səkˈsɛs/" },
      { english: "Technology", turkish: "Teknoloji", example: "Technology is advancing.", exampleTurkish: "Teknoloji ilerliyor.", partOfSpeech: "noun", phonetics: "/tɛkˈnɒlədʒi/" },
      { english: "Truth", turkish: "Gerçek", example: "Tell me the truth.", exampleTurkish: "Bana gerçeği söyle.", partOfSpeech: "noun", phonetics: "/truːθ/" },
      { english: "Value", turkish: "Değer", example: "What is the value?", exampleTurkish: "Değer nedir?", partOfSpeech: "noun", phonetics: "/ˈvæljuː/" },
      { english: "Victory", turkish: "Zafer", example: "We celebrate our victory.", exampleTurkish: "Zaferimizi kutluyoruz.", partOfSpeech: "noun", phonetics: "/ˈvɪktəri/" },
      { english: "Violence", turkish: "Şiddet", example: "Say no to violence.", exampleTurkish: "Şiddete hayır de.", partOfSpeech: "noun", phonetics: "/ˈvaɪələns/" },
      { english: "Ability", turkish: "Yetenek", example: "She has the ability to lead.", exampleTurkish: "Liderlik yeteneği var.", partOfSpeech: "noun", phonetics: "/əˈbɪlɪti/" },
      { english: "Achievement", turkish: "Başarı", example: "This is a great achievement.", exampleTurkish: "Bu harika bir başarı.", partOfSpeech: "noun", phonetics: "/əˈtʃiːvmənt/" },
      { english: "Ambition", turkish: "Hırs", example: "She has ambition.", exampleTurkish: "Hırsı var.", partOfSpeech: "noun", phonetics: "/æmˈbɪʃən/" },
      { english: "Anxiety", turkish: "Kaygı", example: "I feel anxiety.", exampleTurkish: "Kaygı hissediyorum.", partOfSpeech: "noun", phonetics: "/æŋˈzaɪəti/" },
      { english: "Authority", turkish: "Otorite", example: "She has authority.", exampleTurkish: "Otoritesi var.", partOfSpeech: "noun", phonetics: "/ɔːˈθɒrɪti/" },
      { english: "Courage", turkish: "Cesaret", example: "You need courage.", exampleTurkish: "Cesarete ihtiyacın var.", partOfSpeech: "noun", phonetics: "/ˈkɜːrɪdʒ/" },
      { english: "Curiosity", turkish: "Merak", example: "Curiosity killed the cat.", exampleTurkish: "Meraktan kedi öldü.", partOfSpeech: "noun", phonetics: "/ˌkjʊəriˈɒsɪti/" },
      { english: "Damage", turkish: "Hasar", example: "The storm caused damage.", exampleTurkish: "Fırtına hasara yol açtı.", partOfSpeech: "noun", phonetics: "/ˈdæmɪdʒ/" },
      { english: "Danger", turkish: "Tehlike", example: "There is danger.", exampleTurkish: "Tehlike var.", partOfSpeech: "noun", phonetics: "/ˈdeɪndʒər/" },
      { english: "Development", turkish: "Gelişme", example: "Development is important.", exampleTurkish: "Gelişme önemlidir.", partOfSpeech: "noun", phonetics: "/dɪˈvɛləpmənt/" },
      { english: "Discussion", turkish: "Tartışma", example: "We had a discussion.", exampleTurkish: "Bir tartışma yaptık.", partOfSpeech: "noun", phonetics: "/dɪˈskʌʃən/" },
      { english: "Economy", turkish: "Ekonomi", example: "The economy is strong.", exampleTurkish: "Ekonomi güçlü.", partOfSpeech: "noun", phonetics: "/ɪˈkɒnəmi/" },
      { english: "Energy", turkish: "Enerji", example: "I have no energy.", exampleTurkish: "Enerjim yok.", partOfSpeech: "noun", phonetics: "/ˈɛnərdʒi/" },
      { english: "Error", turkish: "Hata", example: "I made an error.", exampleTurkish: "Bir hata yaptım.", partOfSpeech: "noun", phonetics: "/ˈɛrər/" },
      { english: "Evidence", turkish: "Kanıt", example: "There is evidence.", exampleTurkish: "Kanıt var.", partOfSpeech: "noun", phonetics: "/ˈɛvɪdəns/" },
      { english: "Expression", turkish: "İfade", example: "That is a nice expression.", exampleTurkish: "Bu güzel bir ifade.", partOfSpeech: "noun", phonetics: "/ɪkˈsprɛʃən/" },
      { english: "Faith", turkish: "İman", example: "I have faith in you.", exampleTurkish: "Sana inancım var.", partOfSpeech: "noun", phonetics: "/feɪθ/" },
      { english: "Feature", turkish: "Özellik", example: "This is a great feature.", exampleTurkish: "Bu harika bir özellik.", partOfSpeech: "noun", phonetics: "/ˈfiːtʃər/" },
      { english: "Foundation", turkish: "Temel", example: "This is the foundation.", exampleTurkish: "Bu temel.", partOfSpeech: "noun", phonetics: "/faʊnˈdeɪʃən/" },
      { english: "Function", turkish: "İşlev", example: "What is the function?", exampleTurkish: "İşlev nedir?", partOfSpeech: "noun", phonetics: "/ˈfʌŋkʃən/" },
      { english: "Generation", turkish: "Nesil", example: "This is the new generation.", exampleTurkish: "Bu yeni nesil.", partOfSpeech: "noun", phonetics: "/ˌdʒɛnəˈreɪʃən/" },
      { english: "Growth", turkish: "Büyüme", example: "Economic growth.", exampleTurkish: "Ekonomik büyüme.", partOfSpeech: "noun", phonetics: "/ɡroʊθ/" },
      { english: "Identity", turkish: "Kimlik", example: "This is my identity.", exampleTurkish: "Bu benim kimliğim.", partOfSpeech: "noun", phonetics: "/aɪˈdɛntɪti/" },
      { english: "Illness", turkish: "Hastalık", example: "She recovered from illness.", exampleTurkish: "Hastalıktan kurtuldu.", partOfSpeech: "noun", phonetics: "/ˈɪlnəs/" },
      { english: "Imagination", turkish: "Hayal gücü", example: "Use your imagination.", exampleTurkish: "Hayal gücünü kullan.", partOfSpeech: "noun", phonetics: "/ɪˌmædʒɪˈneɪʃən/" },
      { english: "Impact", turkish: "Etki", example: "This has a big impact.", exampleTurkish: "Büyük bir etkisi var.", partOfSpeech: "noun", phonetics: "/ˈɪmpækt/" },
      { english: "Income", turkish: "Gelir", example: "What is your income?", exampleTurkish: "Gelirin nedir?", partOfSpeech: "noun", phonetics: "/ˈɪnkʌm/" },
      { english: "Individual", turkish: "Birey", example: "Each individual has rights.", exampleTurkish: "Her bireyin hakları var.", partOfSpeech: "noun", phonetics: "/ˌɪndɪˈvɪdʒuəl/" },
      { english: "Initiative", turkish: "Girişim", example: "He took the initiative.", exampleTurkish: "Girişimi o başlattı.", partOfSpeech: "noun", phonetics: "/ɪˈnɪʃətɪv/" },
      { english: "Innovation", turkish: "Yenilik", example: "Innovation drives progress.", exampleTurkish: "Yenilik ilerlemeyi sağlar.", partOfSpeech: "noun", phonetics: "/ˌɪnəˈveɪʃən/" },
      { english: "Insight", turkish: "İçgörü", example: "You have great insight.", exampleTurkish: "Harika bir içgörün var.", partOfSpeech: "noun", phonetics: "/ˈɪnsaɪt/" },
      { english: "Interest", turkish: "İlgi", example: "I have an interest in music.", exampleTurkish: "Müziğe ilgim var.", partOfSpeech: "noun", phonetics: "/ˈɪntrɛst/" },
      { english: "Issue", turkish: "Sorun", example: "What is the issue?", exampleTurkish: "Sorun ne?", partOfSpeech: "noun", phonetics: "/ˈɪʃuː/" },
      { english: "Judgment", turkish: "Yargı", example: "Use good judgment.", exampleTurkish: "İyi yargı kullan.", partOfSpeech: "noun", phonetics: "/ˈdʒʌdʒmənt/" },
      { english: "Justice", turkish: "Adalet", example: "Justice must be served.", exampleTurkish: "Adalet yerini bulmalı.", partOfSpeech: "noun", phonetics: "/ˈdʒʌstɪs/" },
      { english: "Liberty", turkish: "Özgürlük", example: "Liberty is important.", exampleTurkish: "Özgürlük önemlidir.", partOfSpeech: "noun", phonetics: "/ˈlɪbərti/" },
      { english: "Limit", turkish: "Sınır", example: "Don't cross the limit.", exampleTurkish: "Sınırı aşma.", partOfSpeech: "noun", phonetics: "/ˈlɪmɪt/" },
      { english: "Logic", turkish: "Mantık", example: "Use logic.", exampleTurkish: "Mantık kullan.", partOfSpeech: "noun", phonetics: "/ˈlɒdʒɪk/" },
      { english: "Loss", turkish: "Kayıp", example: "We suffered a loss.", exampleTurkish: "Bir kayıp yaşadık.", partOfSpeech: "noun", phonetics: "/lɒs/" },
      { english: "Maintenance", turkish: "Bakım", example: "Car needs maintenance.", exampleTurkish: "Araba bakıma ihtiyaç duyuyor.", partOfSpeech: "noun", phonetics: "/ˈmeɪntənəns/" },
      { english: "Management", turkish: "Yönetim", example: "Good management is key.", exampleTurkish: "İyi yönetim önemlidir.", partOfSpeech: "noun", phonetics: "/ˈmænɪdʒmənt/" },
      { english: "Measure", turkish: "Ölçü", example: "Take measures.", exampleTurkish: "Ölçü al.", partOfSpeech: "noun", phonetics: "/ˈmɛʒər/" },
      { english: "Medicine", turkish: "İlaç", example: "Take your medicine.", exampleTurkish: "İlacını al.", partOfSpeech: "noun", phonetics: "/ˈmɛdɪsɪn/" },
      { english: "Message", turkish: "Mesaj", example: "I got your message.", exampleTurkish: "Mesajını aldım.", partOfSpeech: "noun", phonetics: "/ˈmɛsɪdʒ/" },
      { english: "Mission", turkish: "Görev", example: "This is my mission.", exampleTurkish: "Bu benim görevim.", partOfSpeech: "noun", phonetics: "/ˈmɪʃən/" },
      { english: "Mystery", turkish: "Gizem", example: "This is a mystery.", exampleTurkish: "Bu bir gizem.", partOfSpeech: "noun", phonetics: "/ˈmɪstəri/" },
      { english: "Objective", turkish: "Hedef", example: "What is the objective?", exampleTurkish: "Hedef nedir?", partOfSpeech: "noun", phonetics: "/əbˈdʒɛktɪv/" },
      { english: "Obstacle", turkish: "Engel", example: "There are many obstacles.", exampleTurkish: "Birçok engel var.", partOfSpeech: "noun", phonetics: "/ˈɒbstəkəl/" },
      { english: "Origin", turkish: "Köken", example: "What is the origin?", exampleTurkish: "Köken nedir?", partOfSpeech: "noun", phonetics: "/ˈɒrɪdʒɪn/" },
      { english: "Outcome", turkish: "Sonuç", example: "What is the outcome?", exampleTurkish: "Sonuç ne?", partOfSpeech: "noun", phonetics: "/ˈaʊtkʌm/" },
      { english: "Passion", turkish: "Tutku", example: "I have passion for music.", exampleTurkish: "Müziğe tutkum var.", partOfSpeech: "noun", phonetics: "/ˈpæʃən/" },
      { english: "Patience", turkish: "Sabır", example: "You need patience.", exampleTurkish: "Sabıra ihtiyacın var.", partOfSpeech: "noun", phonetics: "/ˈpeɪʃəns/" },
      { english: "Perception", turkish: "Algı", example: "Your perception is interesting.", exampleTurkish: "Algın ilginç.", partOfSpeech: "noun", phonetics: "/pərˈsɛpʃən/" },
      { english: "Perspective", turkish: "Bakış açısı", example: "From my perspective...", exampleTurkish: "Benim bakış açıma göre...", partOfSpeech: "noun", phonetics: "/pərˈspɛktɪv/" },
      { english: "Philosophy", turkish: "Felsefe", example: "This is my philosophy.", exampleTurkish: "Bu benim felsefem.", partOfSpeech: "noun", phonetics: "/fɪˈlɒsəfi/" },
      { english: "Platform", turkish: "Platform", example: "This is a learning platform.", exampleTurkish: "Bu bir öğrenme platformu.", partOfSpeech: "noun", phonetics: "/ˈplætfɔːrm/" },
      { english: "Policy", turkish: "Politika", example: "What is the policy?", exampleTurkish: "Politika nedir?", partOfSpeech: "noun", phonetics: "/ˈpɒlɪsi/" },
      { english: "Possession", turkish: "Sahiplik", example: "These are my possessions.", exampleTurkish: "Bunlar benim eşyalarım.", partOfSpeech: "noun", phonetics: "/pəˈzɛʃən/" },
      { english: "Prayer", turkish: "Dua", example: "I say my prayers.", exampleTurkish: "Dualarımı ederim.", partOfSpeech: "noun", phonetics: "/prɛr/" },
      { english: "Preparation", turkish: "Hazırlık", example: "Preparation is important.", exampleTurkish: "Hazırlık önemlidir.", partOfSpeech: "noun", phonetics: "/ˌprɛpəˈreɪʃən/" },
      { english: "Presence", turkish: "Varlık", example: "Your presence is important.", exampleTurkish: "Varlığınız önemli.", partOfSpeech: "noun", phonetics: "/ˈprɛzəns/" },
      { english: "Presentation", turkish: "Sunum", example: "I gave a presentation.", exampleTurkish: "Bir sunum yaptım.", partOfSpeech: "noun", phonetics: "/ˌprɛzənˈteɪʃən/" },
      { english: "Pride", turkish: "Gurur", example: "I am proud of you.", exampleTurkish: "Seninle gurur duyuyorum.", partOfSpeech: "noun", phonetics: "/praɪd/" },
      { english: "Principle", turkish: "İlke", example: "This is my principle.", exampleTurkish: "Bu benim ilkem.", partOfSpeech: "noun", phonetics: "/ˈprɪnsɪpəl/" },
      { english: "Product", turkish: "Ürün", example: "This is a new product.", exampleTurkish: "Bu yeni bir ürün.", partOfSpeech: "noun", phonetics: "/ˈprɒdʌkt/" },
      { english: "Profession", turkish: "Meslek", example: "What is your profession?", exampleTurkish: "Mesleğin ne?", partOfSpeech: "noun", phonetics: "/prəˈfɛʃən/" },
      { english: "Proposal", turkish: "Teklif", example: "I have a proposal.", exampleTurkish: "Bir teklifim var.", partOfSpeech: "noun", phonetics: "/prəˈpoʊzəl/" },
      { english: "Recommendation", turkish: "Öneri", example: "I have a recommendation.", exampleTurkish: "Bir önerim var.", partOfSpeech: "noun", phonetics: "/ˌrɛkəmɛnˈdeɪʃən/" },
      { english: "Reform", turkish: "Reform", example: "We need reform.", exampleTurkish: "Reforma ihtiyacımız var.", partOfSpeech: "noun", phonetics: "/rɪˈfɔːrm/" },
      { english: "Regret", turkish: "Pişmanlık", example: "I feel regret.", exampleTurkish: "Pişmanlık hissediyorum.", partOfSpeech: "noun", phonetics: "/rɪˈɡrɛt/" },
      { english: "Relief", turkish: "Rahatlama", example: "I feel relief.", exampleTurkish: "Rahatlama hissediyorum.", partOfSpeech: "noun", phonetics: "/rɪˈliːf/" },
      { english: "Reputation", turkish: "İtibar", example: "He has a good reputation.", exampleTurkish: "İyi bir itibarı var.", partOfSpeech: "noun", phonetics: "/ˌrɛpjʊˈteɪʃən/" },
      { english: "Resource", turkish: "Kaynak", example: "We have many resources.", exampleTurkish: "Birçok kaynağımız var.", partOfSpeech: "noun", phonetics: "/rɪˈsɔːrs/" },
      { english: "Response", turkish: "Yanıt", example: "I am waiting for a response.", exampleTurkish: "Bir yanıt bekliyorum.", partOfSpeech: "noun", phonetics: "/rɪˈspɒns/" },
      { english: "Revolution", turkish: "Devrim", example: "This is a revolution.", exampleTurkish: "Bu bir devrim.", partOfSpeech: "noun", phonetics: "/ˌrɛvəˈluːʃən/" },
      { english: "Ritual", turkish: "Ritüel", example: "This is a daily ritual.", exampleTurkish: "Bu günlük bir ritüel.", partOfSpeech: "noun", phonetics: "/ˈrɪtʃuəl/" },
      { english: "Routine", turkish: "Rutin", example: "This is my routine.", exampleTurkish: "Bu benim rutinim.", partOfSpeech: "noun", phonetics: "/ruːˈtiːn/" },
      { english: "Sacrifice", turkish: "Kurban", example: "This is a sacrifice.", exampleTurkish: "Bu bir kurban.", partOfSpeech: "noun", phonetics: "/ˈsækrɪfaɪs/" },
      { english: "Solution", turkish: "Çözüm", example: "I have a solution.", exampleTurkish: "Bir çözümüm var.", partOfSpeech: "noun", phonetics: "/səˈluːʃən/" },
      { english: "Spirit", turkish: "Ruh", example: "The spirit is high.", exampleTurkish: "Ruh hali yüksek.", partOfSpeech: "noun", phonetics: "/ˈspɪrɪt/" },
      { english: "Standard", turkish: "Standart", example: "This is the standard.", exampleTurkish: "Bu standart.", partOfSpeech: "noun", phonetics: "/ˈstændərd/" },
      { english: "Statement", turkish: "Beyanat", example: "I made a statement.", exampleTurkish: "Bir beyanat verdim.", partOfSpeech: "noun", phonetics: "/ˈsteɪtmənt/" },
      { english: "Status", turkish: "Durum", example: "What is the status?", exampleTurkish: "Durum ne?", partOfSpeech: "noun", phonetics: "/ˈsteɪtəs/" },
      { english: "Strategy", turkish: "Strateji", example: "We need a strategy.", exampleTurkish: "Bir stratejiye ihtiyacımız var.", partOfSpeech: "noun", phonetics: "/ˈstrætədʒi/" },
      { english: "Struggle", turkish: "Mücadele", example: "Life is a struggle.", exampleTurkish: "Hayat bir mücadele.", partOfSpeech: "noun", phonetics: "/ˈstrʌɡəl/" },
      { english: "Suggestion", turkish: "Öneri", example: "I have a suggestion.", exampleTurkish: "Bir önerim var.", partOfSpeech: "noun", phonetics: "/səˈdʒɛstʃən/" },
      { english: "Supply", turkish: "Arz", example: "We have supply.", exampleTurkish: "Arzımız var.", partOfSpeech: "noun", phonetics: "/səˈplaɪ/" },
      { english: "Support", turkish: "Destek", example: "I need your support.", exampleTurkish: "Desteğine ihtiyacım var.", partOfSpeech: "noun", phonetics: "/səˈpɔːrt/" },
      { english: "Surface", turkish: "Yüzey", example: "The surface is smooth.", exampleTurkish: "Yüzey pürüzsüz.", partOfSpeech: "noun", phonetics: "/ˈsɜːrfɪs/" },
      { english: "Symbol", turkish: "Sembol", example: "This is a symbol of peace.", exampleTurkish: "Bu barış sembolü.", partOfSpeech: "noun", phonetics: "/ˈsɪmbəl/" },
      { english: "Tendency", turkish: "Eğilim", example: "There is a tendency.", exampleTurkish: "Bir eğilim var.", partOfSpeech: "noun", phonetics: "/ˈtɛndənsi/" },
      { english: "Territory", turkish: "Bölge", example: "This is our territory.", exampleTurkish: "Bu bizim bölgemiz.", partOfSpeech: "noun", phonetics: "/ˈtɛrɪtɔːri/" },
      { english: "Theme", turkish: "Tema", example: "What is the theme?", exampleTurkish: "Tema nedir?", partOfSpeech: "noun", phonetics: "/θiːm/" },
      { english: "Theory", turkish: "Teori", example: "This is just a theory.", exampleTurkish: "Bu sadece bir teori.", partOfSpeech: "noun", phonetics: "/ˈθɪəri/" },
      { english: "Tolerance", turkish: "Hoşgörü", example: "We need tolerance.", exampleTurkish: "Hoşgörüye ihtiyacımız var.", partOfSpeech: "noun", phonetics: "/ˈtɒlərəns/" },
      { english: "Tradition", turkish: "Gelenek", example: "This is a tradition.", exampleTurkish: "Bu bir gelenek.", partOfSpeech: "noun", phonetics: "/trəˈdɪʃən/" },
      { english: "Treatment", turkish: "Tedavi", example: "The treatment worked.", exampleTurkish: "Tedavi işe yaradı.", partOfSpeech: "noun", phonetics: "/ˈtriːtmənt/" },
      { english: "Trend", turkish: "Trend", example: "This is the new trend.", exampleTurkish: "Bu yeni trend.", partOfSpeech: "noun", phonetics: "/trɛnd/" },
      { english: "Trial", turkish: "Deneme", example: "This is a trial.", exampleTurkish: "Bu bir deneme.", partOfSpeech: "noun", phonetics: "/ˈtraɪəl/" },
      { english: "Unity", turkish: "Birlik", example: "Unity is strength.", exampleTurkish: "Birlik kuvvettir.", partOfSpeech: "noun", phonetics: "/ˈjuːnɪti/" },
      { english: "Variety", turkish: "Çeşitlilik", example: "We have variety.", exampleTurkish: "Çeşitliliğimiz var.", partOfSpeech: "noun", phonetics: "/vəˈraɪəti/" },
      { english: "Vehicle", turkish: "Araç", example: "This is a vehicle.", exampleTurkish: "Bu bir araç.", partOfSpeech: "noun", phonetics: "/ˈviːɪkəl/" },
      { english: "Version", turkish: "Sürüm", example: "What version is this?", exampleTurkish: "Bu hangi sürüm?", partOfSpeech: "noun", phonetics: "/ˈvɜːrʒən/" },
      { english: "Vision", turkish: "Vizyon", example: "He has a vision.", exampleTurkish: "Bir vizyonu var.", partOfSpeech: "noun", phonetics: "/ˈvɪʒən/" },
      { english: "Volunteer", turkish: "Gönüllü", example: "I am a volunteer.", exampleTurkish: "Ben gönüllüyüm.", partOfSpeech: "noun", phonetics: "/ˌvɒlənˈtɪr/" },
      { english: "Welfare", turkish: "Refah", example: "Social welfare is important.", exampleTurkish: "Sosyal refah önemlidir.", partOfSpeech: "noun", phonetics: "/ˈwɛlfɛr/" },
      { english: "Witness", turkish: "Tanık", example: "I am a witness.", exampleTurkish: "Ben bir tanığım.", partOfSpeech: "noun", phonetics: "/ˈwɪtnəs/" },
      { english: "Zone", turkish: "Bölge", example: "This is a restricted zone.", exampleTurkish: "Bu kısıtlı bir bölge.", partOfSpeech: "noun", phonetics: "/zoʊn/" },
    ]
  }
];
// Levels B1 through C2 and niche packs are loaded from the full data file
// Full word data is in levels-data.js for performance
